# Generated by Django 5.2 on 2025-05-05 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('idacc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('trípode', 'Trípode'), ('filtro', 'Filtro')], max_length=50)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camara',
            fields=[
                ('idcam', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('DSLR', 'DSLR'), ('dron', 'Dron')], max_length=10)),
                ('valor_mercado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografo',
            fields=[
                ('idfot', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_cliente', models.CharField(choices=[('estudiante', 'Estudiante'), ('profesional', 'Profesional')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('idpre', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateField()),
                ('seguro_activo', models.BooleanField(default=True)),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fotografia.camara')),
                ('fotografo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fotografia.fotografo')),
            ],
        ),
        migrations.CreateModel(
            name='PrestamoAccesorio',
            fields=[
                ('idpa', models.AutoField(primary_key=True, serialize=False)),
                ('accesorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fotografia.accesorio')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fotografia.prestamo')),
            ],
        ),
    ]
